---
- name: Check for installed brews
  shell: brew list | cat
  register: installed_brews
  ignore_errors: true
  failed_when: false

- name: Install brews
  homebrew: name={{ item }} state=present
  with_items: brew_apps
  when: item not in installed_brews.stdout_lines

- name: Install homebrew cask
  homebrew: name=caskroom/cask/brew-cask state=present
  when: '"brew-cask" not in installed_brews.stdout_lines'

- name: Install php brews
  homebrew: name=homebrew/php/{{ item }} state=present
  with_items: brew_php_apps
  when: item not in installed_brews.stdout_lines

- name: Check for installed casks
  shell: brew cask list | cat
  register: installed_casks
  ignore_errors: true
  failed_when: false

- name: Install cask apps
  shell: brew cask install {{ item }}
  with_items: cask_apps
  when: item not in installed_casks.stdout_lines

- name: Install brews (with cask dependencies)
  homebrew: name={{ item }} state=present
  with_items: brew_postcask_apps
  when: item not in installed_brews.stdout_lines

- name: Remove unwanted applications from the dock
  shell: scripts/removeDockApp.sh
